[package]
name = "betfair-stream-api"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[features]
integration-test = ["dep:rustls-pemfile"]

[dependencies]
betfair-stream-types.workspace = true
betfair-adapter.workspace = true
url.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio-rustls.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
futures.workspace = true
futures-concurrency.workspace = true
futures-util.workspace = true
serde.workspace = true
rustls.workspace = true
chrono.workspace = true
eyre.workspace = true
rustls-native-certs.workspace = true
trait-variant.workspace = true
itertools.workspace = true
backoff.workspace = true
rustls-pemfile = { workspace = true, optional = true }
pin-project.workspace = true

[dev-dependencies]
rust_decimal_macros.workspace = true
rust_decimal.workspace = true
eyre.workspace = true
chrono.workspace = true
wiremock.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
test-log.workspace = true
betfair-stream-server-mock.workspace = true
betfair-rpc-server-mock.workspace = true
