[package]
name = "betfair-xml-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-xml-rs.workspace = true
serde.workspace = true
rstest.workspace = true
