[workspace]
resolver = "2"
members = [
  "crates/*",
]

[workspace.dependencies]
# Async
tokio = { version = "1.0", features = ["full", "tracing"] }

# Parsing
serde-xml-rs = "0.6.0"

# HTTP
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "gzip",
  "deflate",
  "rustls-tls",
  "stream",
] }
