[workspace]
resolver = "2"
members = ["crates/*", "crates/betfair-types/betfair-xml-parser"]

[workspace.dependencies]
# Async
tokio = { version = "1.0", features = ["full", "tracing"] }

# Parsing
serde-xml-rs = "0.6"
serde = { version = "1.0", features = ["derive"] }

# HTTP
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "gzip",
  "deflate",
  "rustls-tls",
  "stream",
] }


# Testnig
rstest = { version = "0.17" }
