[package]
name = "betfair-rpc-server-mock"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
betfair-adapter.workspace = true
betfair-types.workspace = true
url.workspace = true
reqwest.workspace = true
serde_json.workspace = true
wiremock.workspace = true
serde.workspace = true
serde_urlencoded.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
rstest.workspace = true
tokio.workspace = true
test-log.workspace = true
wiremock.workspace = true
rust_decimal_macros.workspace = true
rust_decimal.workspace = true
pretty_assertions.workspace = true
