[package]
name = "betfair-typegen"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
betfair-xml-parser.workspace = true
quote.workspace = true
proc-macro2.workspace = true
rust_decimal.workspace = true

[dev-dependencies]
rstest.workspace = true
