[package]
name = "betfair-rpc-adapter"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde_json.workspace = true
betfair-types.workspace = true
