[net]
git-fetch-with-cli = true

[build]
# for some reason, enabling this causes cargo clippy to get stuck
# rustflags = ["-Z", "threads=8", "-Ctarget-cpu=native", "-Zthreads=10"]

[alias]
xtask = "run --package xtask --"
