[package]
name = "betfair-types"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
serde.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
typed-builder.workspace = true

[build-dependencies]
betfair-typegen.workspace = true
