[package]
name = "betfair-types"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[lints]
workspace = true

[dependencies]
serde.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
rust_decimal_macros.workspace = true
typed-builder.workspace = true
redact.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[build-dependencies]
betfair-typegen.workspace = true

[dev-dependencies]
rstest.workspace = true
json-rpc-types.workspace = true

[package.metadata.cargo-machete]
ignored = ["chrono", "typed-builder"]
