[package]
name = "betfair-xml-parser"
version = "0.1.0"
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
serde-xml-rs.workspace = true
serde.workspace = true

[dev-dependencies]
rstest.workspace = true
