[package]
name = "betfair-stream-types"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[lints]
workspace = true

[dependencies]
serde.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
typed-builder.workspace = true
betfair-types.workspace = true
serde_json.workspace = true

[dev-dependencies]
json-rpc-types.workspace = true
