permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
name: test
jobs:
  required:
    runs-on: ubuntu-22.04
    name: ubuntu / ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: [nightly]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2

      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets

  coverage:
    runs-on: ubuntu-22.04
    name: ubuntu / nightly / coverage
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2

      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: cargo llvm-cov clean
        run: cargo llvm-cov clean --workspace

      - name: cargo llvm-cov
        run: cargo llvm-cov --locked --all-features --no-report --release

      - name: cargo llvm-cov report
        run: cargo llvm-cov report --release --lcov --output-path lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
